files:
  - source: /en/*.json
    translation: /%locale_with_underscore%/%original_file_name%
    languages_mapping:
      locale_with_underscore:
        af_ZA: af
        ar_SA: ar
        ca_ES: ca
        cs_CZ: cs
        da_DK: da
        nl_NL: nl
        fi_FI: fi
        fr_FR: fr
        de_DE: de
        el_GR: el
        he_IL: he
        hu_HU: hu
        it_IT: it
        ja_JP: ja
        ko_KR: ko
        no_NO: "no"
        pl_PL: pl
        ro_RO: ro
        ru_RU: ru
        sr_SP: sr
        tr_TR: tr
        uk_UA: uk
        vi_VN: vi
