"commit_message": "Fix: some"                
"append_commit_message": false
files:
  - source: /en/*.json
    translation: /%two_letters_code%/%original_file_name%
    translation_replace:
      ge: en
